---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Load cluster config
    import_tasks: load-config.yml

  - name: Dump config YAML to {{ openshift_provision_cluster_name }}-vars.yaml
    copy:
      content: "{{ lookup('vars', 'vars') | to_nice_yaml(indent=2) }}"
      dest: "{{ playbook_dir }}/{{ openshift_provision_cluster_name }}-vars.yaml"
