---
- name: Fail if cluster_name is not defined
  fail:
    msg: cluster_name must be defined
  when: cluster_name is not defined

- name: Load cluster main vars
  include_vars:
    file: "{{ openshift_config_location }}/cluster/{{ cluster_name }}/vars/main.yml"
    name: _config_main

- name: Load default vars
  include_vars:
    dir: "{{ openshift_config_location }}/default/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load deployment_type vars
  include_vars:
    dir: "{{ openshift_config_location }}/deployment_type/{{ _config_main.deployment_type }}/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load openshift_release vars
  include_vars:
    dir: "{{ openshift_config_location }}/openshift_release/{{ _config_main.openshift_release }}/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load cloud provider vars
  include_vars:
    dir: "{{ openshift_config_location }}/cloud_provider/{{ _config_main.cloud_provider }}/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load cloud region vars
  include_vars:
    dir: "{{ openshift_config_location }}/cloud_region/{{ _config_main.cloud_region }}/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load environment level vars
  include_vars:
    dir: "{{ openshift_config_location }}/environment_level/{{ _config_main.environment_level }}/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load sandbox vars
  include_vars:
    dir: "{{ openshift_config_location }}/sandbox/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'
  when: _config_main.is_sandbox | default(False) | bool

- name: Load cluster vars
  include_vars:
    dir: "{{ openshift_config_location }}/cluster/{{ cluster_name }}/vars"
    files_matching: '^[a-zA-Z0-9].*\.(json|ya?ml)$'

- name: Load dynamic vars
  include_tasks: "{{ dynamic_vars_file.src }}"
  with_filetree:
  - "{{ openshift_config_location }}/dynamic"
  loop_control:
    loop_var: dynamic_vars_file
  when:
    dynamic_vars_file.path is match('.*\.(ya?ml|json)$')
