---
- name: Create tempfile GPG key generation
  tempfile:
    state: file
  register: temp_gpg_gen_conf

- name: Create GPG key gen conf
  copy:
    content: |-
      %echo Generating a basic OpenPGP key
      Key-Type: RSA
      Key-Length: 2048
      Subkey-Type: RSA
      Subkey-Length: 2048
      Name-Real: {{ openshift_provision_gpg_key_name }}
      Name-Email: {{ openshift_provision_gpg_key_email }}
      Expire-Date: 0
      Passphrase: {{ openshift_provision_gpg_key_passphrase }}
      %commit
      %echo done
    dest: "{{ temp_gpg_gen_conf.path }}"
    mode: u=rw,go=

- name: Remove tempfile for GPG key generation
  file:
    path: "{{ temp_gpg_gen_conf.path }}"
    state: absent
