---
- name: Disable yum cron on controller
  include_tasks: disable-yum-cron.yml

- name: Register controller with subscription-manager
  include_tasks: subscription-manager.yml
  when: openshift_deployment_type == 'openshift-enterprise'

- name: Configure yum repos for controller
  include_tasks: origin-yum-repos.yml
  when: openshift_deployment_type == 'origin'

- name: Install packages on controller
  include_tasks: packages.yml

- name: Configure dnsmasq on controller for cloud DNS
  include_tasks: cluster-domain-dns.yml
  when: openshift_provision_cluster_domain_dns_servers is defined

- name: Copy openshift-provision-demo to controller
  include_tasks: openshift-provision-demo-init.yml

- name: Install terraform on controller
  include_tasks: install-terraform.yml

- name: Run rngd to feed entroy to the kernel
  include_tasks: rngd.yml

- name: Create SSH controller ansible keypair
  include_tasks: ssh-keygen.yml

- name: GPG
  include_tasks: gpg.yml

- name: Setup for ansible-vault
  include_tasks: setup-ansible-vault.yml

- name: Controller generated config
  include_tasks: controller-generated-config.yml

- name: Git clone openshift-ansible
  include_tasks: openshift-ansible-git.yml

- name: Include cloud provider specific configuration
  include_tasks: cloud-provider-{{ openshift_provision_cloud_provider }}.yml

- name: Setup user environment
  include_tasks: user-env.yml

- name: Setup gitlab
  include_tasks: gitlab.yml
