---
- include_tasks: disable-yum-cron.yml

- include_tasks: subscription-manager.yml
  when: openshift_deployment_type == 'openshift-enterprise'

- include_tasks: origin-yum-repos.yml
  when: openshift_deployment_type == 'origin'

- include_tasks: packages.yml

- include_tasks: cluster-domain-dns.yml
  when: openshift_provision_cluster_domain_dns_servers is defined

- include_tasks: openshift-provision-demo-init.yml

- include_tasks: install-terraform.yml

- name: Run rngd to feed entroy to the kernel
  include_tasks: rngd.yml

- include_tasks: ssh-keygen.yml

- name: GPG
  include_tasks: gpg.yml

- name: TLS cert generation
  include_tasks: tls-cert-generation.yml

- name: Controller generated config
  include_tasks: controller-generated-config.yml

- name: Git clone openshift-ansible
  include_tasks: openshift-ansible-git.yml

- name: Include cloud provider specific configuration
  include_tasks: cloud-provider-{{ openshift_provision_cloud_provider }}.yml
