---
- name: Set fact for openshift_provision_cluster_tls_dir
  set_fact:
    openshift_provision_cluster_tls_dir: >-
      ~{{ openshift_provision_controller_ansible_user }}/openshift-provision-demo/config/cluster/{{ openshift_provision_cluster_name }}/tls

- name: Create self-signed master cert
  command: >-
    openssl req -new -nodes -x509
    -newkey rsa:2048
    -days 365
    -keyout {{ openshift_provision_cluster_tls_dir }}/master.key
    -out {{ openshift_provision_cluster_tls_dir }}/master.crt
    -subj '/CN={{ openshift_master_cluster_public_hostname }}'
  args:
    creates: "{{ openshift_provision_cluster_tls_dir }}/master.crt"
  register: create_master_certificate

- name: Copy master self signed sert to master-ca.crt
  when: create_master_certificate.changed
  copy:
    remote_src: true
    src: "{{ openshift_provision_cluster_tls_dir }}/master.crt"
    dest: "{{ openshift_provision_cluster_tls_dir }}/master-ca.crt"

- name: Copy master ca cert to /etc/pki/ca-trust/source/anchors
  become: true
  copy:
    remote_src: true
    src: "{{ openshift_provision_cluster_tls_dir }}/master-ca.crt"
    dest: /etc/pki/ca-trust/source/anchors/{{ openshift_provision_cluster_name }}-master-ca.crt
  register: copy_master_ca_cert_to_anchors

- name: Create self-signed router cert
  command: >-
    openssl req -new -nodes -x509
    -newkey rsa:2048
    -days 365
    -keyout {{ openshift_provision_cluster_tls_dir }}/router.key
    -out {{ openshift_provision_cluster_tls_dir }}/router.crt
    -subj '/CN=*.{{ openshift_master_default_subdomain }}'
  args:
    creates: "{{ openshift_provision_cluster_tls_dir }}/router.crt"
  register: create_router_certificate
  vars:
    tls_dir: "~/openshift-provision-demo/config/cluster/{{ openshift_provision_cluster_name }}/tls"

- name: Copy router self signed sert to router-ca.crt
  when: create_router_certificate.changed
  become: false
  copy:
    remote_src: true
    src: "{{ openshift_provision_cluster_tls_dir }}/router.crt"
    dest: "{{ openshift_provision_cluster_tls_dir }}/router-ca.crt"


- name: Copy router ca cert to /etc/pki/ca-trust/source/anchors
  become: true
  copy:
    remote_src: true
    src: "{{ openshift_provision_cluster_tls_dir }}/router-ca.crt"
    dest: /etc/pki/ca-trust/source/anchors/{{ openshift_provision_cluster_name }}-router-ca.crt
  register: copy_router_ca_cert_to_anchors


- name: Update CA trust
  become: true
  command: update-ca-trust
  when: copy_master_ca_cert_to_anchors.changed or copy_router_ca_cert_to_anchors.changed
