---
- name: Set OPENSHIFT_PROVISION_CLUSTER_NAME in ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: "export OPENSHIFT_PROVISION_CLUSTER_NAME={{ openshift_provision_cluster_name }}"

- name: Set OPENSHIFT_PROVISION_CONFIG_PATH in ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: "export OPENSHIFT_PROVISION_CONFIG_PATH=~/openshift-provision-demo/config"

- name: Set OPENSHIFT_ANSIBLE_PATH in ~/.bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: "export OPENSHIFT_ANSIBLE_PATH=~/openshift-ansible"

- name: Set Subscription env vars
  lineinfile:
    path: ~/.bash_profile
    line: "export {{ item }}={{ lookup('env', item) | quote }}"
  when: lookup('env', item)
  with_items:
  - REDHAT_SUBSCRIPTION_USERNAME
  - REDHAT_SUBSCRIPTION_PASSWORD
  - REDHAT_SUBSCRIPTION_POOLS
  - OREG_AUTH_USER
  - OREG_AUTH_PASSWORD
