---
openshift_provision_cluster_name: okd-gcp
openshift_provision_sandbox: true
environment_level: nonprod
cloud_region: gcp-us-central1
cloud_provider: gcp
openshift_release: v3.10
openshift_deployment_type: origin
