---
openshift_provision_cluster_name: okd-gcp
openshift_provision_sandbox: true
openshift_provision_environment_level: nonprod
openshift_provision_cloud_region: gcp-us-central1
openshift_provision_cloud_provider: gcp
openshift_release: v3.10
openshift_deployment_type: origin
