---
openshift_provision_cluster_name: gcp-demo-sbx-ocp-v3-11
openshift_provision_sandbox: true
environment_level: nonprod
cloud_region: gcp-us-east4
cloud_provider: gcp
openshift_release: "3.11"
openshift_deployment_type: openshift-enterprise
