---
- name: Run terrafom destroy
  hosts: localhost
  connection: local
  tasks:
  - name: Load cluster config
    import_tasks: ../load-dynamic-config.yml

  - name: Include terraform role to destroy controller
    include_role:
      name: "{{ openshift_provision_cloud_provider }}-terraform"
      allow_duplicates: true
    vars:
      terraform_action: destroy
      terraform_components:
      - controller
      - network
      terraform_dir: "{{ playbook_dir }}/terraform/{{ openshift_provision_cluster_name }}"
