---
#
# If openshift_provision_management_source_ip_range is not defined then set
# it based on the current systems apparent public ip address.
#

- when:
  - openshift_provision_management_source_ip_range is not defined
  - not openshift_provision_is_running_from_controller|default(False)
  block:
  - name: Determine public ip address
    uri:
      url: http://ipv4bot.whatismyipaddress.com/
      return_content: true
    register: get_whatismyipaddress

  - name: Set openshift_provision_management_source_ip_range
    set_fact:
      openshift_provision_management_source_ip_range: "{{ get_whatismyipaddress.content }}/32"
