---
- include_tasks: terraform-plugins-dir.yml

- include_tasks: terraform-state-bucket.yml

- include_tasks: terraform-setup.yml
  with_items:
  - cluster-core
  - masters
  - image-node
  loop_control:
    loop_var: terraform_template
  vars:
    terraform_template_dir: "{{ terraform_dir }}/{{ terraform_template }}"

- include_tasks: terraform-setup.yml
  with_dict: "{{ openshift_provision_node_groups }}"
  loop_control:
    loop_var: node_group_item
  vars:
    node_group: "{{ node_group_item.value }}"
    node_group_name: "{{ node_group_item.key }}"
    terraform_template: node-group
    terraform_template_dir: "{{ terraform_dir }}/node-group-{{ node_group_name }}"
  when: node_group_name != 'master'

- include_tasks: terraform-{{ openshift_provision_action }}.yml
  when: openshift_provision_action is defined
