---
openshift_gcp_create_network: true
openshift_gcp_image: >-
  {{ 'centos-7' if openshift_deployment_type == 'origin' else 'rhel-7' }}
openshift_gcp_network_name: "{{ cluster_name }}"
openshift_provision_ansible_ssh_pubkey: ''
openshift_provision_ansible_user: ansible
openshift_provision_gcp_subnetwork_name: "{{ cluster_name }}"
openshift_provision_gcp_subnetwork_ip_cidr_range: '10.0.0.0/24'

openshift_provision_use_controller: true
openshift_provision_controller_ansible_port: 22
openshift_provision_controller_ansible_ssh_pubkey: ''
openshift_provision_controller_ansible_user: ansible
openshift_provision_controller_hostname: controller.{{ openshift_provision_dns_cluster_domain }}
openshift_provision_gcp_controller_boot_disk_image: >-
  {{ openshift_gcp_image }}
openshift_provision_gcp_controller_boot_disk_size_gb: 50
openshift_provision_gcp_controller_iam_roles:
- editor
openshift_provision_gcp_controller_machine_type: n1-standard-1
openshift_provision_gcp_controller_service_account: "{{ openshift_gcp_prefix }}controller"

openshift_provision_gcp_dns_delegation_zone_name: ''

openshift_provision_gcp_master_boot_disk_image: >-
  {{ openshift_gcp_image }}
openshift_provision_gcp_master_boot_disk_size_gb: 50
openshift_provision_gcp_master_boot_disk_type: pd-standard
openshift_provision_gcp_master_docker_vg_disk_size_gb: 50
openshift_provision_gcp_master_docker_vg_disk_type: pd-standard
openshift_provision_gcp_master_machine_type: n1-standard-4
openshift_provision_gcp_master_service_account: "{{ openshift_gcp_prefix }}master"

openshift_provision_gcp_node_boot_disk_size_gb: 50
openshift_provision_gcp_node_boot_disk_type: pd-standard
openshift_provision_gcp_node_image_family: "{{ openshift_gcp_prefix }}node"
openshift_provision_gcp_node_machine_type: n1-standard-4
openshift_provision_gcp_node_service_account: "{{ openshift_gcp_prefix }}node"

terraform_action: none
terraform_components:
- base
- masters
- node-groups
