---
openshift_gcp_network_name: "{{ cluster_name }}"
openshift_gcp_subnetwork_name: "{{ cluster_name }}"

openshift_gcp_controller_boot_disk_image: rhel-7
openshift_gcp_controller_boot_disk_size_gb: 50
openshift_gcp_controller_machine_type: n1-standard-1
openshift_gcp_controller_service_account: "{{ openshift_gcp_prefix }}controller"
openshift_provision_controller_ssh_tcp443: false

openshift_provision_master_count: 1
openshift_gcp_master_boot_disk_image: rhel-7
openshift_gcp_master_boot_disk_size_gb: 50
openshift_gcp_master_docker_vg_disk_size_gb: 50
openshift_gcp_master_machine_type: n1-standard-4
openshift_gcp_master_service_account: "{{ openshift_gcp_prefix }}master"

openshift_gcp_node_boot_disk_image: rhel-7
openshift_gcp_node_boot_disk_size_gb: 50
openshift_gcp_node_boot_disk_type: pd-standard
openshift_gcp_node_machine_type: n1-standard-4
openshift_gcp_node_service_account: "{{ openshift_gcp_prefix }}node"

terraform_action: none
terraform_components:
- base
- masters
- node-groups
