---
- name: Create self-signed master public cert
  command: >-
    openssl req -new -nodes -x509
    -newkey rsa:2048
    -days 365
    -keyout {{ openshift_provision_cluster_tls_dir }}/master.key
    -out {{ openshift_provision_cluster_tls_dir }}/master.crt
    -subj '/CN={{ openshift_master_cluster_public_hostname }}'
  args:
    creates: "{{ openshift_provision_cluster_tls_dir }}/master.crt"
  register: create_master_certificate

- when: create_master_certificate.changed
  name: Copy master self signed sert to master-ca.crt
  copy:
    remote_src: true
    src: "{{ openshift_provision_cluster_tls_dir }}/master.crt"
    dest: "{{ openshift_provision_cluster_tls_dir }}/master-ca.crt"

- name: Copy master ca cert to /etc/pki/ca-trust/source/anchors
  become: true
  copy:
    remote_src: true
    src: "{{ openshift_provision_cluster_tls_dir }}/master-ca.crt"
    dest: /etc/pki/ca-trust/source/anchors/{{ openshift_provision_cluster_name }}-master-ca.crt
  ignore_errors: true
  notify: update-ca-trust
