---
- name: Create self-signed router cert
  command: >-
    openssl req -new -nodes -x509
    -newkey rsa:2048
    -days 365
    -keyout {{ openshift_provision_cluster_tls_dir }}/router.key
    -out {{ openshift_provision_cluster_tls_dir }}/router.crt
    -subj '/CN=*.{{ openshift_master_default_subdomain }}'
  args:
    creates: "{{ openshift_provision_cluster_tls_dir }}/router.crt"
  register: create_router_certificate

- name: Copy router self signed sert to router-ca.crt
  when: create_router_certificate.changed
  copy:
    remote_src: true
    src: "{{ openshift_provision_cluster_tls_dir }}/router.crt"
    dest: "{{ openshift_provision_cluster_tls_dir }}/router-ca.crt"

- name: Copy router ca cert to /etc/pki/ca-trust/source/anchors
  become: true
  copy:
    remote_src: true
    src: "{{ openshift_provision_cluster_tls_dir }}/router-ca.crt"
    dest: /etc/pki/ca-trust/source/anchors/{{ openshift_provision_cluster_name }}-router-ca.crt
  register: copy_router_ca_cert_to_anchors
  notify: update-ca-trust

- when: use_shared_public_load_balancer
  block:
  - name: Copy router self signed key to master
    copy:
      remote_src: true
      src: "{{ openshift_provision_cluster_tls_dir }}/router.key"
      dest: "{{ openshift_provision_cluster_tls_dir }}/master.key"
  - name: Copy router self signed cert to master
    copy:
      remote_src: true
      src: "{{ openshift_provision_cluster_tls_dir }}/router.crt"
      dest: "{{ openshift_provision_cluster_tls_dir }}/master.crt"
  - name: Copy router self signed ca cert to master
    copy:
      remote_src: true
      src: "{{ openshift_provision_cluster_tls_dir }}/router-ca.crt"
      dest: "{{ openshift_provision_cluster_tls_dir }}/master-ca.crt"
