---
- name: Load cluster config
  hosts: OSEv3
  vars:
    terraform_dir: "{{ playbook_dir }}/terraform"

  tasks:
  - name: Load cluster config
    import_tasks: ../load-config.yml

- import_playbook: >-
   {{ openshift_ansible_location }}/common/private/components.yml
