---
- name: Load dynamic config
  hosts: OSEv3
  pre_tasks:
  - name: Load dynamic config
    import_tasks: ../load-dynamic-config.yml

- name: Static node preparation
  max_fail_percentage: 0
  hosts: static-nodes
  roles:
  - role: node-prep

- import_playbook: image-node-install-v{{ openshift_release }}.yml
