---
- name: Run terraform destroy
  hosts: localhost
  connection: local
  tasks:
  - name: Load dynamic config
    import_tasks: ../load-dynamic-config.yml

  - name: Include terraform role for destroy
    include_role:
      name: "{{ cloud_provider }}-terraform"
      allow_duplicates: true
    vars:
      terraform_action: destroy
      terraform_components:
      - image-node
      - masters
      - node-groups
      terraform_dir: "{{ playbook_dir }}/terraform"
