---
- name: Run terrafom bootstrap
  hosts: localhost
  connection: local
  tasks:
  - name: Load dynamic config
    import_tasks: ../load-dynamic-config.yml

  - name: Include terraform role for bootstrap
    include_role:
      name: "{{ openshift_provision_cloud_provider }}-terraform"
      allow_duplicates: true
    vars:
      terraform_action: apply
      terraform_components:
      - network
      - service-accounts
      - registry-storage
      terraform_dir: "{{ playbook_dir }}/terraform/{{ openshift_provision_cluster_name }}"

  - name: Refresh inventory
    meta: refresh_inventory
