---
- name: Run terrafom for controller
  hosts: localhost
  connection: local
  tasks:
  - name: Load cluster config
    import_tasks: ../load-config.yml

  - name: Include terraform role for bootstrap
    include_role:
      name: "{{ cloud_provider }}-terraform"
      openshift_provision_action: controller
      terraform_dir: "{{ playbook_dir }}/terraform"

#  - name: Wait for all instances to be running
#    command: ./hosts.py --wait 300
#    changed_when: false
#
#  - name: Refresh inventory
#    meta: refresh_inventory
