---
- name: Get provisioner token
  command: >-
    oc serviceaccounts get-token -n default provisioner
  changed_when: false
  register: get_provisioner_token

- name: Save provisioner token with ansible-vault
  command: >-
    ansible-vault encrypt --vault-password-file={{ vault_password_file }}
    --output={{ cluster_config_path }}/openshift-connection.yml
  args:
    stdin: |-
      {% if openshift_provision_wildcard_dns %}
      openshift_connection_insecure_skip_tls_verify: true
      {% else %}
      openshift_connection_certificate_authority: {{ lookup('file', cluster_config_path ~ '/tls/master-ca.crt') }}
      {% endif %}
      openshift_connection_server: https://{{ openshift_master_cluster_public_hostname }}/
      openshift_connection_token: {{ get_provisioner_token.stdout | to_json }}
  delegate_to: localhost
  register: encrypt_provisioner_token
