---
- name: Create provisioner service account
  command: >-
    oc create serviceaccount -n default provisioner
  register: create_provisioner_serviceaccount
  changed_when: >-
    create_provisioner_serviceaccount.rc == 0
  failed_when: >-
    create_provisioner_serviceaccount.rc != 0 and
    'already exists' not in create_provisioner_serviceaccount.stderr

- name: Cluster provisioner cluster-admin access
  include_tasks: cluster-admin-provisioner.yml

- name: Record openshift connection settings
  include_tasks: configure-openshift-connection.yml
