---
openshift_provision_controller_cloud_packages:
- python2-google-api-client

openshift_provision_controller_cloud_packages_enablerepo:
- epel

openshift_provision_controller_cloud_python_packages: []
