---
openshift_cloudprovider_kind: gce
openshift_gcp_prefix: "{{ openshift_provision_cluster_name }}-"
openshift_gcp_multizone: true
openshift_provision_gcp_node_image_family: "{{ openshift_gcp_prefix }}node"

# FIXME - Support these settings
#openshift_gcp_create_registry_bucket: true
#openshift_gcp_clusterid: default
#openshift_gcp_master_lb_timeout: 2m
#openshift_gcp_registry_bucket_keyfile: ''
#openshift_gcp_registry_bucket_name: "{{ openshift_gcp_prefix }}-docker-registry"

openshift_provision_gcp_use_fqdn: false

openshift_provision_gcp_terraform_state_bucket: "{{ openshift_gcp_project }}-{{ openshift_gcp_prefix }}terraform-state"
