---
openshift_gcp_network_name: "{{ openshift_provision_cluster_name }}"
openshift_gcp_network_project: "{{ openshift_gcp_project }}"
openshift_provision_gcp_subnetwork_name: "{{ openshift_provision_cluster_name }}"
#openshift_provision_gcp_subnetwork_ip_cidr_range: "10.0.0.0/24"

openshift_provision_gcp_dns_zone_name: "{{ openshift_provision_cluster_name }}"
